### ISSUE TITLE
Error While Parsing UFTP_v4_transfer.pcapng

### ISSUE THREAD

**Issue by rghtd** [rghtd/pcapmap#1]
File Downloaded from here:
https://wiki.wireshark.org/SampleCaptures

pcapmap.py ~/Downloads/UFTP_v4_transfer.pcapng
[+][0] New Host Found!  IP Addr: 10.0.0.2
[+][0] New Host Found!  IP Addr: 224.0.0.22
[+][2] New Host Found!  IP Addr: 10.0.0.1
[+][2] New Host Found!  IP Addr: 230.4.4.1
Traceback (most recent call last):
  File "pcapmap.py", line 235, in <module>
    packets = sniff(offline=pcap_file, prn=parse_packet, store=0)
  File "/usr/local/lib/python3.7/site-packages/scapy/sendrecv.py", line 886, in sniff
    r = prn(p)
  File "pcapmap.py", line 37, in parse_packet
    host_list.add_host(packet[IP].src, Host.HOST_SRC)
  File "/usr/local/lib/python3.7/site-packages/scapy/packet.py", line 1079, in __getitem__
    raise IndexError("Layer [%s] not found" % lname)
IndexError: Layer [IP] not found

**Comment by rghtd** [comment]
Seems to be fixed after code-restructure
